### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by LucasHang** [pavlovtech/NextBlog#2]
Just suggesting in case you don't know, but you can use `redirects` in next.config.js instead of putting a `redirect` in your root page.tsx.

[About Next redirects](https://nextjs.org/docs/app/api-reference/next-config-js/redirects)

``` typescript
const nextConfig = {
    redirects: async () => {
        return [
            {
                source: '/',
                destination: '/blog',
                permanent: true,
            },
        ];
     },
    ...
}
```
Great job by the way

**Comment by pavlovtech** [comment]
Nice catch, thanks!
